// Code generated by mockery v1.0.0. DO NOT EDIT.

package image

import mock "github.com/stretchr/testify/mock"

// MockProcessor is an autogenerated mock type for the Processor type
type MockProcessor struct {
	mock.Mock
}

// ProcessImage provides a mock function with given fields: resource
func (_m *MockProcessor) ProcessImage(resource *Resource) error {
	ret := _m.Called(resource)

	var r0 error
	if rf, ok := ret.Get(0).(func(*Resource) error); ok {
		r0 = rf(resource)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
