// Code generated by mockery v1.0.0. DO NOT EDIT.

package provider

import image "github.com/hyperscale/hyperpic/image"
import mock "github.com/stretchr/testify/mock"

// MockSourceProvider is an autogenerated mock type for the SourceProvider type
type MockSourceProvider struct {
	mock.Mock
}

// Del provides a mock function with given fields: resource
func (_m *MockSourceProvider) Del(resource *image.Resource) error {
	ret := _m.Called(resource)

	var r0 error
	if rf, ok := ret.Get(0).(func(*image.Resource) error); ok {
		r0 = rf(resource)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: resource
func (_m *MockSourceProvider) Get(resource *image.Resource) (*image.Resource, error) {
	ret := _m.Called(resource)

	var r0 *image.Resource
	if rf, ok := ret.Get(0).(func(*image.Resource) *image.Resource); ok {
		r0 = rf(resource)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*image.Resource)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*image.Resource) error); ok {
		r1 = rf(resource)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Set provides a mock function with given fields: resource
func (_m *MockSourceProvider) Set(resource *image.Resource) error {
	ret := _m.Called(resource)

	var r0 error
	if rf, ok := ret.Get(0).(func(*image.Resource) error); ok {
		r0 = rf(resource)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
